// Single source of product image paths (mirrors the maps used by the Shop page
// and product detail page) so the Merchant feed and future consumers agree.
export const productImages: Record<string, string> = {
  'heavy-duty-double-zip-tie-handcuff': '/assets/CT handcuffs .jpg.jpeg',
  'bolt-seal': '/assets/bolt-seal.jpg',
  'cable-seal-500mm': '/assets/cable-lock.jpg',
  'abs-cable-lock': '/assets/abs-cable-seal.jpg',
  'cable-seal-300mm': '/assets/cable-lock.jpg',
  'suregas-seal': '/assets/suretite.jpg',
  'nylock-seal': '/assets/nylock.jpg',
  'padlock-seal': '/assets/padlock.jpg',
  'twinlock': '/assets/twinlock.jpg',
  'twinlock-barcoded': '/assets/twinlock.jpg',
  'suretite-barcoded': '/assets/suretite.jpg',
  'suretite-230mm': '/assets/suretite.jpg',
  'suretite-320mm': '/assets/suretite.jpg',
  // Security Bags
  'cash-bags': '/assets/security-bag.jpg',
  'till-bag': '/assets/security-bag.jpg',
  'envopoly': '/assets/envopoly.jpg',
  // Plastic Cable Ties
  'ct-100mm': '/assets/CT black.jpg',
  'ct-150mm': '/assets/CT black.jpg',
  'ct-200mm': '/assets/CT black.jpg',
  'ct-slim-200mm': '/assets/CT black.jpg',
  'ct-heavy-duty-200mm': '/assets/CT black.jpg',
  'ct-300mm': '/assets/CT black.jpg',
  'ct-heavy-duty-300mm': '/assets/CT black.jpg',
  'ct-400mm': '/assets/CT black.jpg',
  'ct-heavy-duty-400mm': '/assets/CT black.jpg',
  'ct-heavy-duty-500mm': '/assets/CT black.jpg',
  'ct-extra-heavy-duty-540mm': '/assets/CT black.jpg',
  // Stainless Steel Cable Ties
  'ss-4-6-150mm': '/assets/SS Cable tie.jpg',
  'ss-4-6-200mm': '/assets/SS Cable tie.jpg',
  'ss-4-6-250mm': '/assets/SS Cable tie.jpg',
  'ss-4-6-300mm': '/assets/SS Cable tie.jpg',
  'ss-4-6-350mm': '/assets/SS Cable tie.jpg',
  'ss-4-6-400mm': '/assets/SS Cable tie.jpg',
  'ss-4-6-450mm': '/assets/SS Cable tie.jpg',
  'ss-4-6-500mm': '/assets/SS Cable tie.jpg',
  'ss-4-6-550mm': '/assets/SS Cable tie.jpg',
  'ss-4-6-600mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-200mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-250mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-300mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-350mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-400mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-450mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-500mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-550mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-600mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-650mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-700mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-750mm': '/assets/SS Cable tie.jpg',
  'ss-7-9-800mm': '/assets/SS Cable tie.jpg',
  'ss-installation-tool': '/assets/CT Installation tool.png',
};