import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import crypto from "crypto";

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Dev-only seed script — mirrors the LIVE 52-product catalog (2026-09-10).
//
// Source of truth:
//   - src/lib/productData.ts quantityTiers (prices are the owner's FINAL NET
//     prices — no VAT mark-up; Product.price = min tier, established rule
//     since commit 58cbb10), plus src/lib/productImages.ts (imageUrl)
//   - live Turso Product table (name, slug, category, description, unit,
//     minOrder, stock)
// Every product insert generates a UUID id (never NULL/empty).
// Safe to re-run: all tables are wiped before insert (idempotent).
// ---------------------------------------------------------------------------

async function main() {
  // Clear existing data (idempotent)
  await prisma.tracking.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.product.deleteMany();
  await prisma.user.deleteMany();

  // Create Admin User (unchanged)
  const adminPasswordHash = await bcrypt.hash("admin123", 12);
  await prisma.user.create({
    data: {
      name: "Admin User",
      email: "admin@ssproc.co.za",
      emailVerified: new Date(),
      passwordHash: adminPasswordHash,
      role: "admin",
    },
  });

  // Create Products (52 — full live catalog)
  const productsData = [
  {
    name: 'Suretite 320mm',
    slug: 'suretite-320mm',
    category: 'Plastic Seals',
    price: 60,
    imageUrl: '/assets/suretite.jpg',
    description: '320mm tamper-evident plastic seal',
    unit: 'Per 50',
    minOrder: 50,
    stock: 100,
  },
  {
    name: 'Suretite 230mm',
    slug: 'suretite-230mm',
    category: 'Plastic Seals',
    price: 870,
    imageUrl: '/assets/suretite.jpg',
    description: '230mm tamper-evident plastic seal',
    unit: 'Per 1000',
    minOrder: 1000,
    stock: 100,
  },
  {
    name: 'Suretite Barcoded',
    slug: 'suretite-barcoded',
    category: 'Plastic Seals',
    price: 1130,
    imageUrl: '/assets/suretite.jpg',
    description: 'Barcoded tamper-evident plastic seal',
    unit: 'Per 1000',
    minOrder: 1000,
    stock: 100,
  },
  {
    name: 'Twinlock',
    slug: 'twinlock',
    category: 'Plastic Seals',
    price: 65,
    imageUrl: '/assets/twinlock.jpg',
    description: 'Twin locking mechanism security seal',
    unit: 'Per 50',
    minOrder: 50,
    stock: 100,
  },
  {
    name: 'Twinlock Barcoded',
    slug: 'twinlock-barcoded',
    category: 'Plastic Seals',
    price: 1130,
    imageUrl: '/assets/twinlock.jpg',
    description: 'Barcoded twinlock security seal',
    unit: 'Per 1000',
    minOrder: 1000,
    stock: 100,
  },
  {
    name: 'Padlock Seal',
    slug: 'padlock-seal',
    category: 'Plastic Seals',
    price: 100,
    imageUrl: '/assets/padlock.jpg',
    description: 'Padlock-style plastic security seal',
    unit: 'Per 50',
    minOrder: 50,
    stock: 100,
  },
  {
    name: 'Nylock Seal',
    slug: 'nylock-seal',
    category: 'Plastic Seals',
    price: 55,
    imageUrl: '/assets/nylock.jpg',
    description: 'Nylon locking seal for general purpose',
    unit: 'Per 40',
    minOrder: 40,
    stock: 100,
  },
  {
    name: 'Bolt Seal',
    slug: 'bolt-seal',
    category: 'Bolt Seals',
    price: 120,
    imageUrl: '/assets/bolt-seal.jpg',
    description: 'Heavy-duty high security bolt seal',
    unit: 'Per 12',
    minOrder: 12,
    stock: 100,
  },
  {
    name: 'Cable Seal 300mm',
    slug: 'cable-seal-300mm',
    category: 'Cable Seals',
    price: 240,
    imageUrl: '/assets/cable-lock.jpg',
    description: '300mm cable seal for container security',
    unit: 'Per 20',
    minOrder: 20,
    stock: 100,
  },
  {
    name: 'Cable Seal 500mm',
    slug: 'cable-seal-500mm',
    category: 'Cable Seals',
    price: 270,
    imageUrl: '/assets/cable-lock.jpg',
    description: '500mm cable seal for heavy-duty applications',
    unit: 'Per 20',
    minOrder: 20,
    stock: 100,
  },
  {
    name: 'ABS Cable Seal',
    slug: 'abs-cable-lock',
    category: 'Cable Seals',
    price: 215,
    imageUrl: '/assets/abs-cable-seal.jpg',
    description: 'ABS plastic cable seal with locking mechanism',
    unit: 'Per 20',
    minOrder: 20,
    stock: 100,
  },
  {
    name: 'Metal Strap (Ball)',
    slug: 'metal-strap-ball',
    category: 'Metal Seals',
    price: 1988,
    imageUrl: '/assets/Ball.jpg',
    description: 'Heavy-duty tamper-evident metal strap seal with ball locking mechanism, silver finish. Sold per 1000.',
    unit: 'Per 1000',
    minOrder: 1000,
    stock: 500,
  },
  {
    name: 'Metal Strap (Flat)',
    slug: 'metal-strap-flat',
    category: 'Metal Seals',
    price: 1988,
    imageUrl: '/assets/Flat.jpg',
    description: 'Heavy-duty tamper-evident metal strap seal with flat locking mechanism, silver finish. Sold per 1000.',
    unit: 'Per 1000',
    minOrder: 1000,
    stock: 500,
  },
  {
    name: 'Cash Bags',
    slug: 'cash-bags',
    category: 'Security Bags',
    price: 52,
    imageUrl: '/assets/security-bag.jpg',
    description: 'Heavy-duty tamper-evident cash bags. Sizes: 26x26cm, 28x35cm, 38x40cm. Colours: Black, Blue, Red, Yellow. Sold per bag.',
    unit: 'Each',
    minOrder: 1,
    stock: 500,
  },
  {
    name: 'Till Bag',
    slug: 'till-bag',
    category: 'Security Bags',
    price: 210,
    imageUrl: '/assets/security-bag.jpg',
    description: 'Heavy-duty tamper-evident till bag, 46 x 36 x 10 cm. Colours: Black, Blue, Red, Yellow. Sold per bag.',
    unit: 'Each',
    minOrder: 1,
    stock: 500,
  },
  {
    name: 'Envopoly',
    slug: 'envopoly',
    category: 'Security Bags',
    price: 185,
    imageUrl: '/assets/envopoly.jpg',
    description: 'One-time use tamper-evident seal for security bags. Per 1000, white only.',
    unit: 'Per 1000',
    minOrder: 1000,
    stock: 500,
  },
  {
    name: 'Heavy Duty Double Zip Tie Handcuff',
    slug: 'heavy-duty-double-zip-tie-handcuff',
    category: 'Plastic Cable Ties',
    price: 280.39,
    imageUrl: '/assets/CT handcuffs .jpg.jpeg',
    description: 'Heavy Duty Double Zip Tie Handcuff - PA66 (Nylon 6/6). Pack of 20.',
    unit: 'Pack of 20',
    minOrder: 20,
    stock: 20,
  },
  {
    name: 'Cable Tie 100mm',
    slug: 'ct-100mm',
    category: 'Plastic Cable Ties',
    price: 12.87,
    imageUrl: '/assets/CT black.jpg',
    description: 'Cable Tie 100mm - PA66 (Nylon 6/6), 100 x 2.5 x 1.1 mm',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'Cable Tie 150mm',
    slug: 'ct-150mm',
    category: 'Plastic Cable Ties',
    price: 25.73,
    imageUrl: '/assets/CT black.jpg',
    description: 'Cable Tie 150mm - PA66 (Nylon 6/6), 150 x 3.6 x 1.3 mm',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'Cable Tie Slim 200mm',
    slug: 'ct-slim-200mm',
    category: 'Plastic Cable Ties',
    price: 37.45,
    imageUrl: '/assets/CT black.jpg',
    description: 'Cable Tie Slim 200mm - PA66 (Nylon 6/6), 200 x 3.6 x 1.1 mm',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'Cable Tie 200mm',
    slug: 'ct-200mm',
    category: 'Plastic Cable Ties',
    price: 42.11,
    imageUrl: '/assets/CT black.jpg',
    description: 'Cable Tie 200mm - PA66 (Nylon 6/6), 200 x 4.8 x 1.3 mm',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'Cable Tie Heavy Duty 200mm',
    slug: 'ct-heavy-duty-200mm',
    category: 'Plastic Cable Ties',
    price: 109.98,
    imageUrl: '/assets/CT black.jpg',
    description: 'Cable Tie Heavy Duty 200mm - PA66 (Nylon 6/6), 200 x 7.6 x 1.9 mm',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'Cable Tie 300mm',
    slug: 'ct-300mm',
    category: 'Plastic Cable Ties',
    price: 70.18,
    imageUrl: '/assets/CT black.jpg',
    description: 'Cable Tie 300mm - PA66 (Nylon 6/6), 300 x 4.8 x 1.3 mm',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'Cable Tie Heavy Duty 300mm',
    slug: 'ct-heavy-duty-300mm',
    category: 'Plastic Cable Ties',
    price: 126.33,
    imageUrl: '/assets/CT black.jpg',
    description: 'Cable Tie Heavy Duty 300mm - PA66 (Nylon 6/6), 300 x 7.6 x 1.9 mm',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'Cable Tie 400mm',
    slug: 'ct-400mm',
    category: 'Plastic Cable Ties',
    price: 84.22,
    imageUrl: '/assets/CT black.jpg',
    description: 'Cable Tie 400mm - PA66 (Nylon 6/6), 400 x 4.8 x 1.3 mm',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'Cable Tie Heavy Duty 400mm',
    slug: 'ct-heavy-duty-400mm',
    category: 'Plastic Cable Ties',
    price: 161.42,
    imageUrl: '/assets/CT black.jpg',
    description: 'Cable Tie Heavy Duty 400mm - PA66 (Nylon 6/6), 400 x 7.6 x 1.9 mm',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'Cable Tie Heavy Duty 500mm',
    slug: 'ct-heavy-duty-500mm',
    category: 'Plastic Cable Ties',
    price: 222.44,
    imageUrl: '/assets/CT black.jpg',
    description: 'Cable Tie Heavy Duty 500mm - PA66 (Nylon 6/6), 500 x 7.6 x 1.9 mm',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'Cable Tie Extra Heavy Duty 540mm',
    slug: 'ct-extra-heavy-duty-540mm',
    category: 'Plastic Cable Ties',
    price: 231.6,
    imageUrl: '/assets/CT black.jpg',
    description: 'Cable Tie Extra Heavy Duty 540mm - PA66 (Nylon 6/6), 540 x 13 x 2.3 mm',
    unit: 'Pack of 50',
    minOrder: 50,
    stock: 50,
  },
  {
    name: 'SS Cable Tie 4.6x150mm',
    slug: 'ss-4-6-150mm',
    category: 'Stainless Steel Cable Ties',
    price: 218.14,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 4.6 x 150 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 4.6x200mm',
    slug: 'ss-4-6-200mm',
    category: 'Stainless Steel Cable Ties',
    price: 249.65,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 4.6 x 200 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 4.6x250mm',
    slug: 'ss-4-6-250mm',
    category: 'Stainless Steel Cable Ties',
    price: 278.74,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 4.6 x 250 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 4.6x300mm',
    slug: 'ss-4-6-300mm',
    category: 'Stainless Steel Cable Ties',
    price: 298.12,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 4.6 x 300 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 4.6x350mm',
    slug: 'ss-4-6-350mm',
    category: 'Stainless Steel Cable Ties',
    price: 344.18,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 4.6 x 350 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 4.6x400mm',
    slug: 'ss-4-6-400mm',
    category: 'Stainless Steel Cable Ties',
    price: 380.54,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 4.6 x 400 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 4.6x450mm',
    slug: 'ss-4-6-450mm',
    category: 'Stainless Steel Cable Ties',
    price: 421.74,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 4.6 x 450 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 4.6x500mm',
    slug: 'ss-4-6-500mm',
    category: 'Stainless Steel Cable Ties',
    price: 458.1,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 4.6 x 500 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 4.6x550mm',
    slug: 'ss-4-6-550mm',
    category: 'Stainless Steel Cable Ties',
    price: 492.03,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 4.6 x 550 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 4.6x600mm',
    slug: 'ss-4-6-600mm',
    category: 'Stainless Steel Cable Ties',
    price: 528.38,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 4.6 x 600 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x200mm',
    slug: 'ss-7-9-200mm',
    category: 'Stainless Steel Cable Ties',
    price: 325.59,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 200 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x250mm',
    slug: 'ss-7-9-250mm',
    category: 'Stainless Steel Cable Ties',
    price: 357.1,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 250 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x300mm',
    slug: 'ss-7-9-300mm',
    category: 'Stainless Steel Cable Ties',
    price: 411.64,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 300 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x350mm',
    slug: 'ss-7-9-350mm',
    category: 'Stainless Steel Cable Ties',
    price: 441.13,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 350 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x400mm',
    slug: 'ss-7-9-400mm',
    category: 'Stainless Steel Cable Ties',
    price: 495.74,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 400 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x450mm',
    slug: 'ss-7-9-450mm',
    category: 'Stainless Steel Cable Ties',
    price: 532.43,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 450 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x500mm',
    slug: 'ss-7-9-500mm',
    category: 'Stainless Steel Cable Ties',
    price: 532.43,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 500 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x550mm',
    slug: 'ss-7-9-550mm',
    category: 'Stainless Steel Cable Ties',
    price: 567.16,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 550 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x600mm',
    slug: 'ss-7-9-600mm',
    category: 'Stainless Steel Cable Ties',
    price: 661.12,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 600 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x650mm',
    slug: 'ss-7-9-650mm',
    category: 'Stainless Steel Cable Ties',
    price: 707.91,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 650 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x700mm',
    slug: 'ss-7-9-700mm',
    category: 'Stainless Steel Cable Ties',
    price: 736.74,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 700 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x750mm',
    slug: 'ss-7-9-750mm',
    category: 'Stainless Steel Cable Ties',
    price: 796.13,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 750 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'SS Cable Tie 7.9x800mm',
    slug: 'ss-7-9-800mm',
    category: 'Stainless Steel Cable Ties',
    price: 833.94,
    imageUrl: '/assets/SS Cable tie.jpg',
    description: 'Stainless Steel 304 cable tie, 7.9 x 800 mm. Corrosion resistant. Pack of 100.',
    unit: 'Pack of 100',
    minOrder: 100,
    stock: 100,
  },
  {
    name: 'Steel Cable Tie Installation Tool',
    slug: 'ss-installation-tool',
    category: 'Stainless Steel Cable Ties',
    price: 1980.34,
    imageUrl: '/assets/CT Installation tool.png',
    description: 'Steel cable tie installation tool for Stainless Steel ties.',
    unit: 'Pack of 1',
    minOrder: 1,
    stock: 1,
  },
  ];

  for (const product of productsData) {
    await prisma.product.create({
      data: { id: crypto.randomUUID(), ...product },
    });
  }
  console.log(`Seeding finished. Products inserted: ${productsData.length}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
